create table accounts (
    id bigint generated by default as identity primary key,
    account_number varchar(20) not null unique,
    owner_name varchar(120) not null,
    balance numeric(19, 2) not null,
    created_at timestamp with time zone not null
);
