create table app_users (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    password_hash varchar(100) not null,
    role varchar(30) not null,
    created_at timestamp with time zone not null
);
